name: Terragrunt Workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the environment to deploy'
        required: true
        default: 'dev'
        options:
          dev: 'Dev'
          stage: 'Stage'
          prod: 'Prod'

jobs:
  terragrunt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform and Terragrunt
        uses: hashicorp/setup-terraform@v1

      - name: Initialize Terragrunt
        uses: the-commons-project/terragrunt-github-actions@master
        run: |
          terragrunt init
        working-directory: ${{ github.event.inputs.environment }}

      - name: Terragrunt Plan
        id: plan
        run: |
          terragrunt plan -out=tfplan
        working-directory: ${{ github.event.inputs.environment }}

      - name: Request Approval
        id: approval
        run: echo "Requesting approval for Terraform changes in ${{ github.event.inputs.environment }}"
      
      - name: Wait for Approval
        if: steps.approval.outcome == 'success'
        run: |
          echo "Waiting for approval..."
          sleep 30  # Adjust the sleep duration as needed
      
      - name: Terragrunt Apply
        if: steps.approval.outcome == 'success'
        run: |
          terragrunt apply -auto-approve tfplan
        working-directory: ${{ github.event.inputs.environment }}
