name: Terraform Workflow

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Terragrunt
      run: |
        wget https://github.com/gruntwork-io/terragrunt/releases/download/v0.34.0/terragrunt_linux_amd64
        chmod +x terragrunt_linux_amd64
        sudo mv terragrunt_linux_amd64 /usr/local/bin/terragrunt

    - name: Terraform Plan
      run: |
        cd path/to/your/terraform/module
        terragrunt init
        terragrunt plan -input=false -out=tfplan

    - name: Request Approval
      id: approval
      run: echo "Approval required to apply changes."

    - name: Terraform Apply
      if: steps.approval.outputs.result == 'approved'
      run: |
        cd path/to/your/terraform/module
        terragrunt apply tfplan